name: Test
on:
  pull_request:
    branches:
      - '**'

jobs:
  release:
    name: test and build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
      - run: npm test
      - run: npm run build
